#+TITLE: Dockerfile of the compiler course
#+AUTHOR: Sholde
#+DATE: June 15, 2021

Provides a *Dockerfile* for the *Compiler Course* by *Pablo de Oliveira
Castro* available here: https://sifflez.org/lectures/compil/

* Dependency

  - ~docker~

  Obviously, you must have docker to build a Dockerfile.

* Usage

  Copy ~Dockerfile~ and ~docker-compose.yml~ next to the root of the compilation project.
  
  In ~docker-compose.yml~ change ~USER~ to your username (the one on your machine) and DIR to the name of the compilation project directory.

  Then start the image with :
  
  #+BEGIN_SRC shell
    $ docker-compose up -d
  #+END_SRC
  
  The first time you lauch the image it will download the base image and install the environnement. This may take some time.

** Detailled Explanation

   The docker-compose file creates a bind mount of your project directory in its home.

   You can work on your project on your machine and the image we see the changes
   you make so you can immediatly test your changes in your docker image without restarting it.
